print (" ############################")
print ("#                            #")
print ("#    Trisna Cahya Permadi    #")
print ("#        2210817210021       #")
print ("#                            #")
print ("##############################")