a=int (input("a= "))
b=int (input("b= "))
i=int (input("i= "))
j=int (input("j= "))
x=int (input("x= "))
y=int (input("y= "))
hasil= (a-b)*(i/j)-(x+y)
print ("hasil dari a dikurang b dikali dengan i dibagi j dikurang dengan x ditambah y adalahl= ", format(hasil, '.3f'))
